spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: MySecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: true